# Generated by Django 5.2.5 on 2025-09-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.FloatField(default=30000),
            preserve_default=False,
        ),
    ]
